version: "3"

services:
  app:
    build: .
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - DB_USER=keycloak
      - DB_PASSWORD=root
    volumes:
      - ./mytheme:/opt/jboss/keycloak/themes/mytheme/
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: root
